[package]
name = "rust-strict-sdp"
version = "0.1.0"
edition = "2021"
description = "SDP parser package used by rust-rcs exclusively"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
